export type ServiceName =
  | 'USER_SERVICE'
  | 'PRODUCT_SERVICE'
  | 'CASHIER_SERVICE'
  | 'STORE_SERVICE'
  | 'UNKNOWN_SERVICE';

export const SERVICE_NAMES_MAPPING: Record<string, ServiceName> = {
  USER_SERVICE: 'USER_SERVICE',
  PRODUCT_SERVICE: 'PRODUCT_SERVICE',
  CASHIER_SERVICE: 'CASHIER_SERVICE',
  STORE_SERVICE: 'STORE_SERVICE',
  UNKNOWN_SERVICE: 'UNKNOWN_SERVICE',
};
