export enum ErrorType {
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  PRISMA_ERROR = 'PRISMA_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  EMPTY_LIST = 'EMPTY_LIST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  CONFLICT = 'CONFLICT',
}
