export enum ErrorType {
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT', // 409 : doublon (email, barcode...)
  FORBIDDEN = 'FORBIDDEN', // 403 : RBAC
  UNAUTHORIZED = 'UNAUTHORIZED', // 401 : token absent/expiré
  UNPROCESSABLE = 'UNPROCESSABLE_ENTITY', // 422 : données valides mais métier KO
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  PRISMA_ERROR = 'PRISMA_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  EMPTY_LIST = 'EMPTY_LIST',
}
